### ISSUE TITLE
recalculate offsetTop or offsetBottom

### ISSUE THREAD

**Issue by alvteren** [codecks-io/react-sticky-box#37]
issue on video https://www.loom.com/share/06e94c9f1e15499099183b53b5e9772c

**Comment by situplastik** [comment]
I have a problem related to, I suposse that @alvteren have the same or more or less ;)

If you try to change the offsetTop parameter during the execution, the plugin doesn't update the parameters and the element continue with the same offsetTop.

In my case is depending oh the screen-width (responsive-desktop). Responsive website have the menu fixed on top (height=50px) and the sticky element must have 50px of offsetTop because if not the element get sticky behind the menu. In order to solve it, I decide to create two Sticky elements and depending of the screen-width I show one or another. The content inside the Sticky

(depending of the the screen-width, stickyTop would be '0' or '50')
```
{stickyTop === 0 && <StickyBox offsetTop={stickyTop}>...</Sticky>}
{stickyTop !== 0 && <StickyBox offsetTop={stickyTop}>....</Sticky>}
```

Anyway, thanks for the plugin, it works really good!

**Comment by danielberndt** [comment]
v2.0.0 was just released which causes the sticky box to recalculate it's position if offsetTop or offsetBottom are changed
