### ISSUE TITLE
Allow for offset

### ISSUE THREAD

**Issue by rafaponieman** [codecks-io/react-sticky-box#5]
It may be the case that the user has a sticky header menu, for example, in which case the sticky elements shouldn't stick to the top of the page, but take that offset into consideration. Otherwise, it works great, thank you!

**Comment by danielberndt** [comment]
The way I usually solve this is to create a transparent wrapper-div around the menu and add a padding to that wrapper-div. Would that work in your situation as well?

**Comment by rafaponieman** [comment]
Hello Daniel, I think it won't work in my case, but I'm not 100% sure.

Here's the link (no sticky box implemented on the live version): https://www.peaksport.com.ar/es/store/hombre/

I'm trying to get the sidebar and the top bar (the one that reads Filtros) to stay. The horizontal bar should stick below the menu, and the sidebar below the horizontal bar.

Thanks!!

**Comment by danielberndt** [comment]
Ah, I see!
Have a look at this example then: https://codesandbox.io/s/9jyjjn05q4

The idea is to create a separate scroll panel for the main content. The sticky boxes will be constrained by this scroll panel

**Comment by rafaponieman** [comment]
That's great, though I think it still won't do cause we may have a transparent menu and a large background image on the first part (currently black), that goes below the menu.

**Comment by danielberndt** [comment]
Understood. It probably makes sense to offer an offset attribute then.
Realistically I won't be able to work on this the next couple of weeks. But if you wan't to you can try it yourself and give it a spin.
The main logic for evaluating whether to stick or to scroll a box can be found here:
https://github.com/codecks-io/react-sticky-box/blob/beef0a34333692edefb94917e587bf124b3a0eba/src/index.js#L114-L168

Since this is a very finicky process I haven't set up any automated test yet. But running `cd examples && yarn install && yarn start` lets you play around with two pages to see whether it's working :)

Extra points for reacting if the user changes the offset-value within `componentWillReceiveProps`

**Comment by danielberndt** [comment]
v0.6.3 was just released adding offset support :)
