### ISSUE TITLE
onChangeMode not working

### ISSUE THREAD

**Issue by beamercola** [codecks-io/react-sticky-box#56]
Hi!  Huge fan of the library.  Right now I'm trying to change the background color of the element when it's stuck.  Everything works perfectly except I don't recieve callbacks when state changes

```js
<StickyBox offsetTop={0} onChangeMode={(o, n) => console.log(o, n)}>
```

I get 3 logs onload,  all `undefined stickyTop` - but then nothing.

HTML structure is quite simple:

<img width="406" alt="Screen Shot 2021-01-21 at 5 55 34 PM" src="https://user-images.githubusercontent.com/8060/105435257-e4ef0080-5c11-11eb-85a4-971423a0d863.png">

**Comment by xessam** [comment]
i recently used it, same here, exactly I get 3 logs with undefined stickyTop and no more,

**Comment by returnvoid** [comment]
I've noticed that this callback is never trigger because the sticky value never changes, it's always sticky

**Comment by danielberndt** [comment]
v1.0.0 was just released which removed the `onChangeMode` callback because it tended to cause misunderstandings of what types of events it would trigger.

To actually trigger the kind of event you are referring to is a bit more involved unfortunately and I'm fairly confident it's out of scope for this library

Check out [this article](https://developers.google.com/web/updates/2017/09/sticky-headers) for one approach of how to detect the desired event.

Maybe there's some react-based implementation out there. In that case I'm fairly confident it's gonna be composable with this library (especially since it now also offers a hook-based version)
